### ISSUE TITLE
better handling of missing values (null) in saveDF

### ISSUE THREAD

**Issue by luyi666** [arangodb/arangodb-spark-connector#19]
A doc can often contain a large number of missing properties. 
It is often the case that `saveDF` method can accept a dataframe which contains many null values. 
the `rowToVPack` method called in `saveRDD` checks row schema only instead of each value in row. 
As a result, `null` slots in the dataframe can be accidentally inserted as string "null". 
![image](https://user-images.githubusercontent.com/20776204/71502826-3e6cea80-28ad-11ea-9f9d-c2e59c070f69.png)

It could be better to filter `null` values in each row before calling `addField`.
``` scala
def rowToVPack(row: Row): VPackSlice = {
    val builder = new VPackBuilder()
    builder.add(ValueType.OBJECT)
    row.schema.fields.zipWithIndex
      // filter possible null properites in the dataframe
      .filter(x=>row.get(x._2) != null)
      .foreach { addField(_, row, builder) }
    builder.close()
    builder.slice()
  }
```
which results
![image](https://user-images.githubusercontent.com/20776204/71502902-b2a78e00-28ad-11ea-8160-6f76977f9c28.png)

**Comment by rashtao** [comment]
For the moment I added explicit handling for `null` values here: https://github.com/arangodb/arangodb-spark-connector/commit/b4db6f643a3c0a1c18c554aea5bd8cc4fa48f173

Now `null` values are never inserted as `"null"` strings, but as `null` values.

Imho, completely removing the null field is not possible, since depending on the use case, the `null` value could represent information different from missing field.

However it could be possible adding a way to configure null and missing fields handling.

**Comment by rashtao** [comment]
This library has been now deprecated in favor of the new [ArangoDB Datasource for Apache Spark](https://github.com/arangodb/arangodb-spark-datasource).
If this issue is still relevant please reopen it in the new connector's project.
